<?php

namespace Proxies\__CG__\Cosanit\CosanitBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Souscropts extends \Cosanit\CosanitBundle\Entity\Souscropts implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'Cosanit\\CosanitBundle\\Entity\\Souscropts' . "\0" . 'id', '' . "\0" . 'Cosanit\\CosanitBundle\\Entity\\Souscropts' . "\0" . 'nom', '' . "\0" . 'Cosanit\\CosanitBundle\\Entity\\Souscropts' . "\0" . 'adresse', '' . "\0" . 'Cosanit\\CosanitBundle\\Entity\\Souscropts' . "\0" . 'email', '' . "\0" . 'Cosanit\\CosanitBundle\\Entity\\Souscropts' . "\0" . 'npermis', '' . "\0" . 'Cosanit\\CosanitBundle\\Entity\\Souscropts' . "\0" . 'catpermis', '' . "\0" . 'Cosanit\\CosanitBundle\\Entity\\Souscropts' . "\0" . 'genre', '' . "\0" . 'Cosanit\\CosanitBundle\\Entity\\Souscropts' . "\0" . 'wilaya', '' . "\0" . 'Cosanit\\CosanitBundle\\Entity\\Souscropts' . "\0" . 'matricule', '' . "\0" . 'Cosanit\\CosanitBundle\\Entity\\Souscropts' . "\0" . 'nserie', '' . "\0" . 'Cosanit\\CosanitBundle\\Entity\\Souscropts' . "\0" . 'ntype', '' . "\0" . 'Cosanit\\CosanitBundle\\Entity\\Souscropts' . "\0" . 'anneecircule', '' . "\0" . 'Cosanit\\CosanitBundle\\Entity\\Souscropts' . "\0" . 'marque', '' . "\0" . 'Cosanit\\CosanitBundle\\Entity\\Souscropts' . "\0" . 'modele', '' . "\0" . 'Cosanit\\CosanitBundle\\Entity\\Souscropts' . "\0" . 'usage', '' . "\0" . 'Cosanit\\CosanitBundle\\Entity\\Souscropts' . "\0" . 'telephone', '' . "\0" . 'Cosanit\\CosanitBundle\\Entity\\Souscropts' . "\0" . 'nbplace', '' . "\0" . 'Cosanit\\CosanitBundle\\Entity\\Souscropts' . "\0" . 'datepermis', '' . "\0" . 'Cosanit\\CosanitBundle\\Entity\\Souscropts' . "\0" . 'photopermis', '' . "\0" . 'Cosanit\\CosanitBundle\\Entity\\Souscropts' . "\0" . 'photocartegrise'];
        }

        return ['__isInitialized__', '' . "\0" . 'Cosanit\\CosanitBundle\\Entity\\Souscropts' . "\0" . 'id', '' . "\0" . 'Cosanit\\CosanitBundle\\Entity\\Souscropts' . "\0" . 'nom', '' . "\0" . 'Cosanit\\CosanitBundle\\Entity\\Souscropts' . "\0" . 'adresse', '' . "\0" . 'Cosanit\\CosanitBundle\\Entity\\Souscropts' . "\0" . 'email', '' . "\0" . 'Cosanit\\CosanitBundle\\Entity\\Souscropts' . "\0" . 'npermis', '' . "\0" . 'Cosanit\\CosanitBundle\\Entity\\Souscropts' . "\0" . 'catpermis', '' . "\0" . 'Cosanit\\CosanitBundle\\Entity\\Souscropts' . "\0" . 'genre', '' . "\0" . 'Cosanit\\CosanitBundle\\Entity\\Souscropts' . "\0" . 'wilaya', '' . "\0" . 'Cosanit\\CosanitBundle\\Entity\\Souscropts' . "\0" . 'matricule', '' . "\0" . 'Cosanit\\CosanitBundle\\Entity\\Souscropts' . "\0" . 'nserie', '' . "\0" . 'Cosanit\\CosanitBundle\\Entity\\Souscropts' . "\0" . 'ntype', '' . "\0" . 'Cosanit\\CosanitBundle\\Entity\\Souscropts' . "\0" . 'anneecircule', '' . "\0" . 'Cosanit\\CosanitBundle\\Entity\\Souscropts' . "\0" . 'marque', '' . "\0" . 'Cosanit\\CosanitBundle\\Entity\\Souscropts' . "\0" . 'modele', '' . "\0" . 'Cosanit\\CosanitBundle\\Entity\\Souscropts' . "\0" . 'usage', '' . "\0" . 'Cosanit\\CosanitBundle\\Entity\\Souscropts' . "\0" . 'telephone', '' . "\0" . 'Cosanit\\CosanitBundle\\Entity\\Souscropts' . "\0" . 'nbplace', '' . "\0" . 'Cosanit\\CosanitBundle\\Entity\\Souscropts' . "\0" . 'datepermis', '' . "\0" . 'Cosanit\\CosanitBundle\\Entity\\Souscropts' . "\0" . 'photopermis', '' . "\0" . 'Cosanit\\CosanitBundle\\Entity\\Souscropts' . "\0" . 'photocartegrise'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Souscropts $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setNom($nom)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNom', [$nom]);

        return parent::setNom($nom);
    }

    /**
     * {@inheritDoc}
     */
    public function getNom()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNom', []);

        return parent::getNom();
    }

    /**
     * {@inheritDoc}
     */
    public function setAdresse($adresse)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAdresse', [$adresse]);

        return parent::setAdresse($adresse);
    }

    /**
     * {@inheritDoc}
     */
    public function getAdresse()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAdresse', []);

        return parent::getAdresse();
    }

    /**
     * {@inheritDoc}
     */
    public function setEmail($email)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmail', [$email]);

        return parent::setEmail($email);
    }

    /**
     * {@inheritDoc}
     */
    public function getEmail()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmail', []);

        return parent::getEmail();
    }

    /**
     * {@inheritDoc}
     */
    public function setNpermis($npermis)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNpermis', [$npermis]);

        return parent::setNpermis($npermis);
    }

    /**
     * {@inheritDoc}
     */
    public function getNpermis()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNpermis', []);

        return parent::getNpermis();
    }

    /**
     * {@inheritDoc}
     */
    public function setCatpermis($catpermis)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCatpermis', [$catpermis]);

        return parent::setCatpermis($catpermis);
    }

    /**
     * {@inheritDoc}
     */
    public function getCatpermis()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCatpermis', []);

        return parent::getCatpermis();
    }

    /**
     * {@inheritDoc}
     */
    public function setGenre($genre)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setGenre', [$genre]);

        return parent::setGenre($genre);
    }

    /**
     * {@inheritDoc}
     */
    public function getGenre()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGenre', []);

        return parent::getGenre();
    }

    /**
     * {@inheritDoc}
     */
    public function setWilaya($wilaya)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setWilaya', [$wilaya]);

        return parent::setWilaya($wilaya);
    }

    /**
     * {@inheritDoc}
     */
    public function getWilaya()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getWilaya', []);

        return parent::getWilaya();
    }

    /**
     * {@inheritDoc}
     */
    public function setMatricule($matricule)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMatricule', [$matricule]);

        return parent::setMatricule($matricule);
    }

    /**
     * {@inheritDoc}
     */
    public function getMatricule()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMatricule', []);

        return parent::getMatricule();
    }

    /**
     * {@inheritDoc}
     */
    public function setNserie($nserie)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNserie', [$nserie]);

        return parent::setNserie($nserie);
    }

    /**
     * {@inheritDoc}
     */
    public function getNserie()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNserie', []);

        return parent::getNserie();
    }

    /**
     * {@inheritDoc}
     */
    public function setNtype($ntype)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNtype', [$ntype]);

        return parent::setNtype($ntype);
    }

    /**
     * {@inheritDoc}
     */
    public function getNtype()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNtype', []);

        return parent::getNtype();
    }

    /**
     * {@inheritDoc}
     */
    public function setAnneecircule($anneecircule)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAnneecircule', [$anneecircule]);

        return parent::setAnneecircule($anneecircule);
    }

    /**
     * {@inheritDoc}
     */
    public function getAnneecircule()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAnneecircule', []);

        return parent::getAnneecircule();
    }

    /**
     * {@inheritDoc}
     */
    public function setMarque($marque)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMarque', [$marque]);

        return parent::setMarque($marque);
    }

    /**
     * {@inheritDoc}
     */
    public function getMarque()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMarque', []);

        return parent::getMarque();
    }

    /**
     * {@inheritDoc}
     */
    public function setModele($modele)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setModele', [$modele]);

        return parent::setModele($modele);
    }

    /**
     * {@inheritDoc}
     */
    public function getModele()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getModele', []);

        return parent::getModele();
    }

    /**
     * {@inheritDoc}
     */
    public function setUsage($usage)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUsage', [$usage]);

        return parent::setUsage($usage);
    }

    /**
     * {@inheritDoc}
     */
    public function getUsage()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUsage', []);

        return parent::getUsage();
    }

    /**
     * {@inheritDoc}
     */
    public function setTelephone($telephone)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTelephone', [$telephone]);

        return parent::setTelephone($telephone);
    }

    /**
     * {@inheritDoc}
     */
    public function getTelephone()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTelephone', []);

        return parent::getTelephone();
    }

    /**
     * {@inheritDoc}
     */
    public function setNbplace($nbplace)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNbplace', [$nbplace]);

        return parent::setNbplace($nbplace);
    }

    /**
     * {@inheritDoc}
     */
    public function getNbplace()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNbplace', []);

        return parent::getNbplace();
    }

    /**
     * {@inheritDoc}
     */
    public function setDatepermis($datepermis)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDatepermis', [$datepermis]);

        return parent::setDatepermis($datepermis);
    }

    /**
     * {@inheritDoc}
     */
    public function getDatepermis()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDatepermis', []);

        return parent::getDatepermis();
    }

    /**
     * {@inheritDoc}
     */
    public function setPhotopermis(\Cosanit\CosanitBundle\Entity\Media $photopermis = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPhotopermis', [$photopermis]);

        return parent::setPhotopermis($photopermis);
    }

    /**
     * {@inheritDoc}
     */
    public function getPhotopermis()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPhotopermis', []);

        return parent::getPhotopermis();
    }

    /**
     * {@inheritDoc}
     */
    public function setPhotocartegrise(\Cosanit\CosanitBundle\Entity\Media $photocartegrise = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPhotocartegrise', [$photocartegrise]);

        return parent::setPhotocartegrise($photocartegrise);
    }

    /**
     * {@inheritDoc}
     */
    public function getPhotocartegrise()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPhotocartegrise', []);

        return parent::getPhotocartegrise();
    }

}
