<?php

namespace Proxies\__CG__\Cosanit\CosanitBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Estimations extends \Cosanit\CosanitBundle\Entity\Estimations implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'Cosanit\\CosanitBundle\\Entity\\Estimations' . "\0" . 'id', '' . "\0" . 'Cosanit\\CosanitBundle\\Entity\\Estimations' . "\0" . 'en', '' . "\0" . 'Cosanit\\CosanitBundle\\Entity\\Estimations' . "\0" . 'type', '' . "\0" . 'Cosanit\\CosanitBundle\\Entity\\Estimations' . "\0" . 'np', '' . "\0" . 'Cosanit\\CosanitBundle\\Entity\\Estimations' . "\0" . 'surfaceh', '' . "\0" . 'Cosanit\\CosanitBundle\\Entity\\Estimations' . "\0" . 'surfacet', '' . "\0" . 'Cosanit\\CosanitBundle\\Entity\\Estimations' . "\0" . 'ville', '' . "\0" . 'Cosanit\\CosanitBundle\\Entity\\Estimations' . "\0" . 'codepostal', '' . "\0" . 'Cosanit\\CosanitBundle\\Entity\\Estimations' . "\0" . 'message', '' . "\0" . 'Cosanit\\CosanitBundle\\Entity\\Estimations' . "\0" . 'nom', '' . "\0" . 'Cosanit\\CosanitBundle\\Entity\\Estimations' . "\0" . 'prenom', '' . "\0" . 'Cosanit\\CosanitBundle\\Entity\\Estimations' . "\0" . 'adresse', '' . "\0" . 'Cosanit\\CosanitBundle\\Entity\\Estimations' . "\0" . 'cpostal', '' . "\0" . 'Cosanit\\CosanitBundle\\Entity\\Estimations' . "\0" . 'ville2', '' . "\0" . 'Cosanit\\CosanitBundle\\Entity\\Estimations' . "\0" . 'tel', '' . "\0" . 'Cosanit\\CosanitBundle\\Entity\\Estimations' . "\0" . 'email', '' . "\0" . 'Cosanit\\CosanitBundle\\Entity\\Estimations' . "\0" . 'mr', '' . "\0" . 'Cosanit\\CosanitBundle\\Entity\\Estimations' . "\0" . 'mme', '' . "\0" . 'Cosanit\\CosanitBundle\\Entity\\Estimations' . "\0" . 'melle', '' . "\0" . 'Cosanit\\CosanitBundle\\Entity\\Estimations' . "\0" . 'photopermis', '' . "\0" . 'Cosanit\\CosanitBundle\\Entity\\Estimations' . "\0" . 'photocartegrise'];
        }

        return ['__isInitialized__', '' . "\0" . 'Cosanit\\CosanitBundle\\Entity\\Estimations' . "\0" . 'id', '' . "\0" . 'Cosanit\\CosanitBundle\\Entity\\Estimations' . "\0" . 'en', '' . "\0" . 'Cosanit\\CosanitBundle\\Entity\\Estimations' . "\0" . 'type', '' . "\0" . 'Cosanit\\CosanitBundle\\Entity\\Estimations' . "\0" . 'np', '' . "\0" . 'Cosanit\\CosanitBundle\\Entity\\Estimations' . "\0" . 'surfaceh', '' . "\0" . 'Cosanit\\CosanitBundle\\Entity\\Estimations' . "\0" . 'surfacet', '' . "\0" . 'Cosanit\\CosanitBundle\\Entity\\Estimations' . "\0" . 'ville', '' . "\0" . 'Cosanit\\CosanitBundle\\Entity\\Estimations' . "\0" . 'codepostal', '' . "\0" . 'Cosanit\\CosanitBundle\\Entity\\Estimations' . "\0" . 'message', '' . "\0" . 'Cosanit\\CosanitBundle\\Entity\\Estimations' . "\0" . 'nom', '' . "\0" . 'Cosanit\\CosanitBundle\\Entity\\Estimations' . "\0" . 'prenom', '' . "\0" . 'Cosanit\\CosanitBundle\\Entity\\Estimations' . "\0" . 'adresse', '' . "\0" . 'Cosanit\\CosanitBundle\\Entity\\Estimations' . "\0" . 'cpostal', '' . "\0" . 'Cosanit\\CosanitBundle\\Entity\\Estimations' . "\0" . 'ville2', '' . "\0" . 'Cosanit\\CosanitBundle\\Entity\\Estimations' . "\0" . 'tel', '' . "\0" . 'Cosanit\\CosanitBundle\\Entity\\Estimations' . "\0" . 'email', '' . "\0" . 'Cosanit\\CosanitBundle\\Entity\\Estimations' . "\0" . 'mr', '' . "\0" . 'Cosanit\\CosanitBundle\\Entity\\Estimations' . "\0" . 'mme', '' . "\0" . 'Cosanit\\CosanitBundle\\Entity\\Estimations' . "\0" . 'melle', '' . "\0" . 'Cosanit\\CosanitBundle\\Entity\\Estimations' . "\0" . 'photopermis', '' . "\0" . 'Cosanit\\CosanitBundle\\Entity\\Estimations' . "\0" . 'photocartegrise'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Estimations $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setEn($en)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEn', [$en]);

        return parent::setEn($en);
    }

    /**
     * {@inheritDoc}
     */
    public function getEn()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEn', []);

        return parent::getEn();
    }

    /**
     * {@inheritDoc}
     */
    public function setType($type)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setType', [$type]);

        return parent::setType($type);
    }

    /**
     * {@inheritDoc}
     */
    public function getType()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getType', []);

        return parent::getType();
    }

    /**
     * {@inheritDoc}
     */
    public function setNp($np)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNp', [$np]);

        return parent::setNp($np);
    }

    /**
     * {@inheritDoc}
     */
    public function getNp()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNp', []);

        return parent::getNp();
    }

    /**
     * {@inheritDoc}
     */
    public function setSurfaceh($surfaceh)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSurfaceh', [$surfaceh]);

        return parent::setSurfaceh($surfaceh);
    }

    /**
     * {@inheritDoc}
     */
    public function getSurfaceh()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSurfaceh', []);

        return parent::getSurfaceh();
    }

    /**
     * {@inheritDoc}
     */
    public function setSurfacet($surfacet)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSurfacet', [$surfacet]);

        return parent::setSurfacet($surfacet);
    }

    /**
     * {@inheritDoc}
     */
    public function getSurfacet()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSurfacet', []);

        return parent::getSurfacet();
    }

    /**
     * {@inheritDoc}
     */
    public function setVille($ville)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVille', [$ville]);

        return parent::setVille($ville);
    }

    /**
     * {@inheritDoc}
     */
    public function getVille()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVille', []);

        return parent::getVille();
    }

    /**
     * {@inheritDoc}
     */
    public function setCodepostal($codepostal)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCodepostal', [$codepostal]);

        return parent::setCodepostal($codepostal);
    }

    /**
     * {@inheritDoc}
     */
    public function getCodepostal()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCodepostal', []);

        return parent::getCodepostal();
    }

    /**
     * {@inheritDoc}
     */
    public function setMessage($message)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMessage', [$message]);

        return parent::setMessage($message);
    }

    /**
     * {@inheritDoc}
     */
    public function getMessage()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMessage', []);

        return parent::getMessage();
    }

    /**
     * {@inheritDoc}
     */
    public function setNom($nom)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNom', [$nom]);

        return parent::setNom($nom);
    }

    /**
     * {@inheritDoc}
     */
    public function getNom()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNom', []);

        return parent::getNom();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrenom($prenom)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrenom', [$prenom]);

        return parent::setPrenom($prenom);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrenom()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrenom', []);

        return parent::getPrenom();
    }

    /**
     * {@inheritDoc}
     */
    public function setAdresse($adresse)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAdresse', [$adresse]);

        return parent::setAdresse($adresse);
    }

    /**
     * {@inheritDoc}
     */
    public function getAdresse()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAdresse', []);

        return parent::getAdresse();
    }

    /**
     * {@inheritDoc}
     */
    public function setCpostal($cpostal)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCpostal', [$cpostal]);

        return parent::setCpostal($cpostal);
    }

    /**
     * {@inheritDoc}
     */
    public function getCpostal()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCpostal', []);

        return parent::getCpostal();
    }

    /**
     * {@inheritDoc}
     */
    public function setVille2($ville2)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVille2', [$ville2]);

        return parent::setVille2($ville2);
    }

    /**
     * {@inheritDoc}
     */
    public function getVille2()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVille2', []);

        return parent::getVille2();
    }

    /**
     * {@inheritDoc}
     */
    public function setTel($tel)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTel', [$tel]);

        return parent::setTel($tel);
    }

    /**
     * {@inheritDoc}
     */
    public function getTel()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTel', []);

        return parent::getTel();
    }

    /**
     * {@inheritDoc}
     */
    public function setEmail($email)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmail', [$email]);

        return parent::setEmail($email);
    }

    /**
     * {@inheritDoc}
     */
    public function getEmail()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmail', []);

        return parent::getEmail();
    }

    /**
     * {@inheritDoc}
     */
    public function setMr($mr)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMr', [$mr]);

        return parent::setMr($mr);
    }

    /**
     * {@inheritDoc}
     */
    public function getMr()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMr', []);

        return parent::getMr();
    }

    /**
     * {@inheritDoc}
     */
    public function setMme($mme)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMme', [$mme]);

        return parent::setMme($mme);
    }

    /**
     * {@inheritDoc}
     */
    public function getMme()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMme', []);

        return parent::getMme();
    }

    /**
     * {@inheritDoc}
     */
    public function setMelle($melle)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMelle', [$melle]);

        return parent::setMelle($melle);
    }

    /**
     * {@inheritDoc}
     */
    public function getMelle()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMelle', []);

        return parent::getMelle();
    }

    /**
     * {@inheritDoc}
     */
    public function setPhotopermis(\Cosanit\CosanitBundle\Entity\Media $photopermis = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPhotopermis', [$photopermis]);

        return parent::setPhotopermis($photopermis);
    }

    /**
     * {@inheritDoc}
     */
    public function getPhotopermis()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPhotopermis', []);

        return parent::getPhotopermis();
    }

    /**
     * {@inheritDoc}
     */
    public function setPhotocartegrise(\Cosanit\CosanitBundle\Entity\Media $photocartegrise = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPhotocartegrise', [$photocartegrise]);

        return parent::setPhotocartegrise($photocartegrise);
    }

    /**
     * {@inheritDoc}
     */
    public function getPhotocartegrise()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPhotocartegrise', []);

        return parent::getPhotocartegrise();
    }

}
