<?php

namespace Cosanit\CosanitBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ActivationsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ActivationsRepository extends EntityRepository
{

    public function findAll()
    {
        return $this->findBy(array(), array('date' => 'DESC'));
    }
}
