<?php

namespace Cosanit\CosanitBundle\Repository;

/**
 * Dc30Repository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Dc30Repository extends \Doctrine\ORM\EntityRepository
{
    public function findAll3moisasc(){
        $qb = $this->createQueryBuilder('u')
            ->select('u')
            ->orderBy('u.taux3mois','ASC')

        ;

        return $qb->getQuery()->getResult();
    }

    public function findAll6moisasc(){
        $qb = $this->createQueryBuilder('u')
            ->select('u')
            ->orderBy('u.taux6mois','ASC')

        ;

        return $qb->getQuery()->getResult();
    }

    public function findAll1anasc(){
        $qb = $this->createQueryBuilder('u')
            ->select('u')
            ->orderBy('u.taux1an','ASC')

        ;

        return $qb->getQuery()->getResult();
    }
}
