<?php

namespace Cosanit\CosanitBundle\Repository;

/**
 * Dc5Repository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Dc5Repository extends \Doctrine\ORM\EntityRepository
{
}
