<?php

namespace Cosanit\CosanitBundle\Repository;

/**
 * DocsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DocsRepository extends \Doctrine\ORM\EntityRepository
{
}
