<?php

namespace Cosanit\CosanitBundle\Repository;

/**
 * EntreprisesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EntreprisesRepository extends \Doctrine\ORM\EntityRepository
{
}
