<?php

namespace Cosanit\CosanitBundle\Repository;

/**
 * EstimationsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EstimationsRepository extends \Doctrine\ORM\EntityRepository
{


    public function findLast(){
        $qb = $this->createQueryBuilder('u')
            ->select('u')
            ->setMaxResults( 1 )
            ->orderBy('u.id','DESC')

        ;
        return $qb->getQuery()->getResult();
    }
}
