<?php

namespace Cosanit\CosanitBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * aproposblockRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PartenairesRepository extends EntityRepository
{
    public function byCategorie($id){
        $qb = $this->createQueryBuilder('u')
            ->select('u')
            ->leftJoin('u.types', 'c')
            ->where('c.slug = :id')
            ->orderBy('u.id','ASC')
            ->setParameter('id',$id);
        return $qb->getQuery()->getResult();
    }
}