<?php

namespace Cosanit\CosanitBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PhotosusersRepository
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PhotosusersRepository extends EntityRepository
{
    public function findBynum($num){
        $qb = $this->createQueryBuilder('u')
            ->select('u')
            ->where('u.email = :email')
            ->orderBy('u.id','DESC')
            ->setParameter('email',$num)

        ;
        return $qb->getQuery()->getResult();
    }
}
