<?php

namespace Cosanit\CosanitBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Symfony\Component\Validator\Constraints\DateTime;

/**
 * SerialsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SerialsRepository extends EntityRepository
{
    public function modif($code,$date){
        $qb = $this->createQueryBuilder('u')
            ->update('CosanitBundle:Serials', 'u')
            ->set('u.active', '?1')
            ->set('u.clientdate', '?3')
            ->where('u.serial = ?2')
            ->setParameter(1, 1)
            ->setParameter(3, $date)
            ->setParameter(2, $code);

        return $qb->getQuery()->getResult();
    }

    public function del($debut,$fin){
        $qb = $this->createQueryBuilder('u')
            ->delete('CosanitBundle:Serials', 'u')

            ->where('u.serial >= ?1 ')
            ->andWhere('u.serial <= ?2')


            ->setParameter(1, $debut)
            ->setParameter(2, $fin)
           ;
        return $qb->getQuery()->getResult();
    }
}
