<?php

namespace Cosanit\CosanitBundle\Repository;

/**
 * SouscroptsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SouscroptsRepository extends \Doctrine\ORM\EntityRepository
{
}
