<?php

namespace Cosanit\CosanitBundle\Repository;

/**
 * SouscriptionsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SouscriptionsRepository extends \Doctrine\ORM\EntityRepository
{
}
