<?php

namespace Cosanit\CosanitBundle\Repository;

/**
 * Trs2Repository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Trs2Repository extends \Doctrine\ORM\EntityRepository
{
}
