admin_Activations_index:
    path:     /
    defaults: { _controller: "CosanitBundle:Activations:index" }
    methods:  GET

admin_Activations_show:
    path:     /{id}/show
    defaults: { _controller: "CosanitBundle:Activations:show" }
    methods:  GET

admin_Activations_new:
    path:     /new
    defaults: { _controller: "CosanitBundle:Activations:new" }
    methods:  [GET, POST]

admin_Activations_edit:
    path:     /{id}/edit
    defaults: { _controller: "CosanitBundle:Activations:edit" }
    methods:  [GET, POST]

admin_Activations_delete:
    path:     /{id}/delete
    defaults: { _controller: "CosanitBundle:Activations:delete" }
    methods:  DELETE
