admin_about_index:
    path:     /
    defaults: { _controller: "CosanitBundle:Apropos:index" }
    methods:  GET

admin_about_show:
    path:     /{id}/show
    defaults: { _controller: "CosanitBundle:Apropos:show" }
    methods:  GET

admin_about_new:
    path:     /new
    defaults: { _controller: "CosanitBundle:Apropos:new" }
    methods:  [GET, POST]

admin_about_edit:
    path:     /{id}/edit
    defaults: { _controller: "CosanitBundle:Apropos:edit" }
    methods:  [GET, POST]

admin_about_delete:
    path:     /{id}/delete
    defaults: { _controller: "CosanitBundle:Apropos:delete" }
    methods:  DELETE
