admin_assistance2_index:
    path:     /
    defaults: { _controller: "CosanitBundle:Assistance2:index" }
    methods:  GET

admin_assistance2_show:
    path:     /{id}/show
    defaults: { _controller: "CosanitBundle:Assistance2:show" }
    methods:  GET

admin_assistance2_new:
    path:     /new
    defaults: { _controller: "CosanitBundle:Assistance2:new" }
    methods:  [GET, POST]

admin_assistance2_edit:
    path:     /{id}/edit
    defaults: { _controller: "CosanitBundle:Assistance2:edit" }
    methods:  [GET, POST]

admin_assistance2_delete:
    path:     /{id}/delete
    defaults: { _controller: "CosanitBundle:Assistance2:delete" }
    methods:  DELETE
