admin_categories_index:
    path:     /
    defaults: { _controller: "CosanitBundle:Categories:index" }
    methods:  GET

admin_categories_show:
    path:     /{id}/show
    defaults: { _controller: "CosanitBundle:Categories:show" }
    methods:  GET

admin_categories_new:
    path:     /new
    defaults: { _controller: "CosanitBundle:Categories:new" }
    methods:  [GET, POST]

admin_categories_edit:
    path:     /{id}/edit
    defaults: { _controller: "CosanitBundle:Categories:edit" }
    methods:  [GET, POST]

admin_categories_delete:
    path:     /{id}/delete
    defaults: { _controller: "CosanitBundle:Categories:delete" }
    methods:  DELETE
