admin_dc30_index:
    path:     /
    defaults: { _controller: "CosanitBundle:Dc30:index" }
    methods:  GET

admin_dc30_show:
    path:     /{id}/show
    defaults: { _controller: "CosanitBundle:Dc30:show" }
    methods:  GET

admin_dc30_new:
    path:     /new
    defaults: { _controller: "CosanitBundle:Dc30:new" }
    methods:  [GET, POST]

admin_dc30_edit:
    path:     /{id}/edit
    defaults: { _controller: "CosanitBundle:Dc30:edit" }
    methods:  [GET, POST]

admin_dc30_delete:
    path:     /{id}/delete
    defaults: { _controller: "CosanitBundle:Dc30:delete" }
    methods:  DELETE
