admin_dc40_index:
    path:     /
    defaults: { _controller: "CosanitBundle:Dc40:index" }
    methods:  GET

admin_dc40_show:
    path:     /{id}/show
    defaults: { _controller: "CosanitBundle:Dc40:show" }
    methods:  GET

admin_dc40_new:
    path:     /new
    defaults: { _controller: "CosanitBundle:Dc40:new" }
    methods:  [GET, POST]

admin_dc40_edit:
    path:     /{id}/edit
    defaults: { _controller: "CosanitBundle:Dc40:edit" }
    methods:  [GET, POST]

admin_dc40_delete:
    path:     /{id}/delete
    defaults: { _controller: "CosanitBundle:Dc40:delete" }
    methods:  DELETE
