admin_entreprise_index:
    path:     /
    defaults: { _controller: "CosanitBundle:Entreprises:index" }
    methods:  GET

admin_entreprise_show:
    path:     /{id}/show
    defaults: { _controller: "CosanitBundle:Entreprises:show" }
    methods:  GET

admin_entreprise_new:
    path:     /new
    defaults: { _controller: "CosanitBundle:Entreprises:new" }
    methods:  [GET, POST]

admin_entreprise_edit:
    path:     /{id}/edit
    defaults: { _controller: "CosanitBundle:Entreprises:edit" }
    methods:  [GET, POST]

admin_entreprise_delete:
    path:     /{id}/delete
    defaults: { _controller: "CosanitBundle:Entreprises:delete" }
    methods:  DELETE
