admin_incendies_index:
    path:     /
    defaults: { _controller: "CosanitBundle:Incendies:index" }
    methods:  GET

admin_incendies_show:
    path:     /{id}/show
    defaults: { _controller: "CosanitBundle:Incendies:show" }
    methods:  GET

admin_incendies_new:
    path:     /new
    defaults: { _controller: "CosanitBundle:Incendies:new" }
    methods:  [GET, POST]

admin_incendies_edit:
    path:     /{id}/edit
    defaults: { _controller: "CosanitBundle:Incendies:edit" }
    methods:  [GET, POST]

admin_incendies_delete:
    path:     /{id}/delete
    defaults: { _controller: "CosanitBundle:Incendies:delete" }
    methods:  DELETE
