admin_logos_index:
    path:     /
    defaults: { _controller: "CosanitBundle:Logos:index" }
    methods:  GET

admin_logos_show:
    path:     /{id}/show
    defaults: { _controller: "CosanitBundle:Logos:show" }
    methods:  GET

admin_logos_new:
    path:     /new
    defaults: { _controller: "CosanitBundle:Logos:new" }
    methods:  [GET, POST]

admin_logos_edit:
    path:     /{id}/edit
    defaults: { _controller: "CosanitBundle:Logos:edit" }
    methods:  [GET, POST]

admin_logos_delete:
    path:     /{id}/delete
    defaults: { _controller: "CosanitBundle:Logos:delete" }
    methods:  DELETE
