admin_mentions_index:
    path:     /
    defaults: { _controller: "CosanitBundle:Mentions:index" }
    methods:  GET

admin_mentions_show:
    path:     /{id}/show
    defaults: { _controller: "CosanitBundle:Mentions:show" }
    methods:  GET

admin_mentions_new:
    path:     /new
    defaults: { _controller: "CosanitBundle:Mentions:new" }
    methods:  [GET, POST]

admin_mentions_edit:
    path:     /{id}/edit
    defaults: { _controller: "CosanitBundle:Mentions:edit" }
    methods:  [GET, POST]

admin_mentions_delete:
    path:     /{id}/delete
    defaults: { _controller: "CosanitBundle:Mentions:delete" }
    methods:  DELETE
