admin_neufs_index:
    path:     /
    defaults: { _controller: "CosanitBundle:Neufs:index" }
    methods:  GET

admin_neufs_show:
    path:     /{id}/show
    defaults: { _controller: "CosanitBundle:Neufs:show" }
    methods:  GET

admin_neufs_new:
    path:     /new
    defaults: { _controller: "CosanitBundle:Neufs:new" }
    methods:  [GET, POST]

admin_neufs_edit:
    path:     /{id}/edit
    defaults: { _controller: "CosanitBundle:Neufs:edit" }
    methods:  [GET, POST]

admin_neufs_delete:
    path:     /{id}/delete
    defaults: { _controller: "CosanitBundle:Neufs:delete" }
    methods:  DELETE

admin_neufs_envois:
    path:     /envois
    defaults: { _controller: "CosanitBundle:Neufs:envois" }
    methods:  [GET, POST]