admin_produits_index:
    path:     /
    defaults: { _controller: "CosanitBundle:Produits:index" }
    methods:  GET

admin_produits_show:
    path:     /{id}/show
    defaults: { _controller: "CosanitBundle:Produits:show" }
    methods:  GET

admin_produits_new:
    path:     /new
    defaults: { _controller: "CosanitBundle:Produits:new" }
    methods:  [GET, POST]

admin_produits_edit:
    path:     /{id}/edit
    defaults: { _controller: "CosanitBundle:Produits:edit" }
    methods:  [GET, POST]

admin_produits_delete:
    path:     /{id}/delete
    defaults: { _controller: "CosanitBundle:Produits:delete" }
    methods:  DELETE
