admin_souscripts_index:
    path:     /
    defaults: { _controller: "CosanitBundle:Souscropts:index" }
    methods:  GET

admin_souscripts_show:
    path:     /{id}/show
    defaults: { _controller: "CosanitBundle:Souscropts:show" }
    methods:  GET

admin_souscripts_new:
    path:     /new
    defaults: { _controller: "CosanitBundle:Souscropts:new" }
    methods:  [GET, POST]

admin_souscripts_edit:
    path:     /{id}/edit
    defaults: { _controller: "CosanitBundle:Souscropts:edit" }
    methods:  [GET, POST]

admin_souscripts_delete:
    path:     /{id}/delete
    defaults: { _controller: "CosanitBundle:Souscropts:delete" }
    methods:  DELETE
