admin_trs2_index:
    path:     /
    defaults: { _controller: "CosanitBundle:Trs2:index" }
    methods:  GET

admin_trs2_show:
    path:     /{id}/show
    defaults: { _controller: "CosanitBundle:Trs2:show" }
    methods:  GET

admin_trs2_new:
    path:     /new
    defaults: { _controller: "CosanitBundle:Trs2:new" }
    methods:  [GET, POST]

admin_trs2_edit:
    path:     /{id}/edit
    defaults: { _controller: "CosanitBundle:Trs2:edit" }
    methods:  [GET, POST]

admin_trs2_delete:
    path:     /{id}/delete
    defaults: { _controller: "CosanitBundle:Trs2:delete" }
    methods:  DELETE
