admin_trs3_index:
    path:     /
    defaults: { _controller: "CosanitBundle:Trs3:index" }
    methods:  GET

admin_trs3_show:
    path:     /{id}/show
    defaults: { _controller: "CosanitBundle:Trs3:show" }
    methods:  GET

admin_trs3_new:
    path:     /new
    defaults: { _controller: "CosanitBundle:Trs3:new" }
    methods:  [GET, POST]

admin_trs3_edit:
    path:     /{id}/edit
    defaults: { _controller: "CosanitBundle:Trs3:edit" }
    methods:  [GET, POST]

admin_trs3_delete:
    path:     /{id}/delete
    defaults: { _controller: "CosanitBundle:Trs3:delete" }
    methods:  DELETE
