admin_users_index:
    path:     /
    defaults: { _controller: "CosanitBundle:User:index" }
    methods:  GET

admin_users_show:
    path:     /{id}/show
    defaults: { _controller: "CosanitBundle:User:show" }
    methods:  GET

admin_users_new:
    path:     /new
    defaults: { _controller: "CosanitBundle:User:new" }
    methods:  [GET, POST]

admin_users_edit:
    path:     /{id}/edit
    defaults: { _controller: "CosanitBundle:User:edit" }
    methods:  [GET, POST]

admin_users_delete:
    path:     /{id}/delete
    defaults: { _controller: "CosanitBundle:User:delete" }
    methods:  DELETE
